/**
  ******************************************************************************
  * @file    audio_chain_fBeamforming.h
  * @author  MCD Application Team
  * @brief   wrapper of frequency beamforming algo to match usage inside audio_chain.c
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2019(-2022) STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __AUDIO_CHAIN_FBEAMFORMING_H
#define __AUDIO_CHAIN_FBEAMFORMING_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "audio_chain.h"
#include "fBeamforming_coef.h"
#define   BF_MAX_ANTENNA_COEFS (129U)
#define   BF_MAX_SRC_ARRAY     (5)

typedef struct
{
  float     real;
  float     imag;
} fbf_coef;

typedef struct
{
  uint16_t     value;
} fbf_src_value;

typedef struct
{
  uint32_t                 nbCoefs;
  fbf_coef                 tCoefs[BF_MAX_ANTENNA_COEFS];
} fbf_coef_array;

typedef struct
{
  uint32_t                 nbCoefs;
  fbf_src_value            tArray[BF_MAX_SRC_ARRAY];
} fbf_src_array;

typedef struct fbf_static_config_t
{
  uint8_t       ramType;

  uint8_t       unitDb;
  /* Flag forced at zero when used with designer but if set at 1 allows to use
  *  legacy API with precomputed coefficients
  */
  uint8_t       is_legacy;

  /* Variable not used by the algo inside the firmware but will be used by the
  *  algorithm on the PC side that will generate the coefficients from these values
  */
  float         plot_freq;   /* used for polar plot rendering */
  uint32_t      sample_freq;
  uint32_t      bands_nb;
  uint8_t       mic_nb;
  uint8_t       mic_dist;
  float         noise_std;
  fbf_src_array speech_sources;
  fbf_src_array interference_sources;

  /* Following fields will host antenna coefs generated by LiveTune
  *  the coefs follows the model struct array and description
  */
  fbf_coef_array tAntennaCoef1;
  fbf_coef_array tAntennaCoef2;

  /* Legacy API = direct pointers to antennas
  */
  FBF_Coeffs_t legacyCoeffs;
} fbf_static_config_t;



/* Exported types ------------------------------------------------------------*/
/* Exported constants --------------------------------------------------------*/
/* Exported variables --------------------------------------------------------*/
extern const audio_algo_factory_t AudioChainWrp_fBeamforming_factory;
extern const audio_algo_common_t  AudioChainWrp_fBeamforming_common;
extern       audio_algo_cbs_t     AudioChainWrp_fBeamforming_cbs;

/* Exported macros -----------------------------------------------------------*/
/* Exported functions ------------------------------------------------------- */


#ifdef __cplusplus
}
#endif

#endif /* __AUDIO_CHAIN_FBEAMFORMING_H */
