/**
******************************************************************************
* @file    audio_chain_algo_list_template.c
* @author  MCD Application Team
* @brief   Helper file that provides a list of algorithm that will appear
*
*******************************************************************************
* @attention
*
* Copyright (c) 2019(-2022) STMicroelectronics.
* All rights reserved.
*
* This software is licensed under terms that can be found in the LICENSE file
* in the root directory of this software component.
* If no LICENSE file comes with this software, it is provided AS-IS.
*
********************************************************************************
*/


/* Includes ------------------------------------------------------------------*/
#include "audio_chain_factory.h"

/* Global variables ----------------------------------------------------------*/
/* generated by the terminal command "algo_list" */

#ifdef ALGO_USE_LIST
  /* 00 capture */
  extern audio_algo_factory_t AudioChainWrp_capture_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_capture_factory);
  /* 01 constantSource */
  extern audio_algo_factory_t AudioChainWrp_constantSource_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_constantSource_factory);
  /* 02 deinterleave */
  extern audio_algo_factory_t AudioChainWrp_deinterleave_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_deinterleave_factory);
  /* 03 delay */
  extern audio_algo_factory_t AudioChainWrp_delay_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_delay_factory);
  /* 04 delay_samples */
  extern audio_algo_factory_t AudioChainWrp_delay_samples_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_delay_samples_factory);
  /* 05 echo */
  extern audio_algo_factory_t AudioChainWrp_echo_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_echo_factory);
  /* 06 faust-chorus */
  extern audio_algo_factory_t AudioChainWrp_soundChorus_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_soundChorus_factory);
  /* 07 faust-compressor */
  extern audio_algo_factory_t AudioChainWrp_faust_compressor_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_faust_compressor_factory);
  /* 08 faust-distortion */
  extern audio_algo_factory_t AudioChainWrp_faust_distortion_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_faust_distortion_factory);
  /* 09 faust-noise-gate */
  extern audio_algo_factory_t AudioChainWrp_faust_noise_gate_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_faust_noise_gate_factory);
  /* 10 faust-phaser */
  extern audio_algo_factory_t AudioChainWrp_faust_phaser_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_faust_phaser_factory);
  /* 11 faust-reverb-dattorro */
  extern audio_algo_factory_t AudioChainWrp_faust_reverb_dattorro_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_faust_reverb_dattorro_factory);
  /* 12 fBeamforming */
  extern audio_algo_factory_t AudioChainWrp_fBeamforming_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_fBeamforming_factory);
  /* 13 fdisjoin */
  extern audio_algo_factory_t AudioChainWrp_fdisjoin_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_fdisjoin_factory);
  /* 14 FIR-equalizer */
  extern audio_algo_factory_t AudioChainWrp_fir_equalizer_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_fir_equalizer_factory);
  /* 15 FIR-graphic-equalizer */
  extern audio_algo_factory_t AudioChainWrp_fir_graphic_equalizer_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_fir_graphic_equalizer_factory);
  /* 16 fjoin */
  extern audio_algo_factory_t AudioChainWrp_fjoin_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_fjoin_factory);
  /* 17 fnlms */
  extern audio_algo_factory_t AudioChainWrp_fnlms_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_fnlms_factory);
  /* 18 g711_dec */
  extern audio_algo_factory_t AudioChainWrp_g711Dec_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_g711Dec_factory);
  /* 19 g711_enc */
  extern audio_algo_factory_t AudioChainWrp_g711Enc_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_g711Enc_factory);
  /* 20 gain */
  extern audio_algo_factory_t AudioChainWrp_gain_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_gain_factory);
  /* 21 hpf */
  extern audio_algo_factory_t AudioChainWrp_hpf_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_hpf_factory);
  /* 22 IIR-equalizer */
  extern audio_algo_factory_t AudioChainWrp_iir_equalizer_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_iir_equalizer_factory);
  /* 23 interleave */
  extern audio_algo_factory_t AudioChainWrp_interleave_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_interleave_factory);
  /* 24 linear_mix */
  extern audio_algo_factory_t AudioChainWrp_linear_mix_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_linear_mix_factory);
  /* 25 mdrc */
  extern audio_algo_factory_t AudioChainWrp_mdrc_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_mdrc_factory);
  /* 26 mix */
  extern audio_algo_factory_t AudioChainWrp_mix_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_mix_factory);
  /* 27 mono2stereo */
  extern audio_algo_factory_t AudioChainWrp_mono2stereo_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_mono2stereo_factory);
  /* 28 nlms */
  extern audio_algo_factory_t AudioChainWrp_nlms_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_nlms_factory);
  /* 29 nr */
  extern audio_algo_factory_t AudioChainWrp_nr_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_nr_factory);
  /* 30 passThrough */
  extern audio_algo_factory_t AudioChainWrp_passThrough_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_passThrough_factory);
  /* 31 resample */
  extern audio_algo_factory_t AudioChainWrp_resample_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_resample_factory);
  /* 32 rms */
  extern audio_algo_factory_t AudioChainWrp_rms_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_rms_factory);
  /* 33 route */
  extern audio_algo_factory_t AudioChainWrp_route_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_route_factory);
  /* 34 sfc */
  extern audio_algo_factory_t AudioChainWrp_sfc_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_sfc_factory);
  /* 35 signal-generator */
  extern audio_algo_factory_t AudioChainWrp_signal_generator_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_signal_generator_factory);
  /* 36 sound-font */
  extern audio_algo_factory_t AudioChainWrp_sound_font_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_sound_font_factory);
  /* 37 spectrum */
  extern audio_algo_factory_t AudioChainWrp_spectrum_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_spectrum_factory);
  /* 38 speex_aec */
  extern audio_algo_factory_t AudioChainWrp_speex_aec_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_speex_aec_factory);
  /* 39 speex_nr */
  extern audio_algo_factory_t AudioChainWrp_speex_nr_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_speex_nr_factory);
  /* 40 split */
  extern audio_algo_factory_t AudioChainWrp_split_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_split_factory);
  /* 41 switch */
  extern audio_algo_factory_t AudioChainWrp_switch_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_switch_factory);
  /* 42 stereo2mono */
  extern audio_algo_factory_t AudioChainWrp_stereo2mono_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_stereo2mono_factory);
  /* 43 wola_fwd */
  extern audio_algo_factory_t AudioChainWrp_wola_fwd_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_wola_fwd_factory);
  /* 44 wola_inv */
  extern audio_algo_factory_t AudioChainWrp_wola_inv_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_wola_inv_factory);
  /* 45 voidSink */
  extern audio_algo_factory_t AudioChainWrp_voidSink_factory;
  ALGO_FACTORY_DECLARE_FORCE(AudioChainWrp_voidSink_factory);
#endif